CREATE TABLE `t_client` (
                          `clientID` int NOT NULL AUTO_INCREMENT,
                          `channelID` int NOT NULL,
                          `wechatID` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
                          `phoneNum` varchar(11) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
                          `standard` char(1) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
                          `payType` char(1) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
                          `status` char(1) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
                          `attentionTime` datetime DEFAULT NULL,
                          `bindTime` datetime DEFAULT NULL,
                          `cancelTime` datetime DEFAULT NULL,
                          `insertUser` int DEFAULT NULL,
                          `insertTime` datetime DEFAULT NULL,
                          `updateUser` int DEFAULT NULL,
                          `updateTime` datetime DEFAULT NULL,
                          `score` int DEFAULT '0',
                          `recommendPhone` varchar(11) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
                          `sceneStr` varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
                          PRIMARY KEY (`clientID`),
                          KEY `channelID` (`channelID`) USING BTREE,
                          KEY `wechatID` (`wechatID`) USING BTREE,
                          KEY `phoneNum` (`phoneNum`) USING BTREE,
                          KEY `standard` (`standard`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;